FROM python:3.8-slim

# Update the local package index with the latest packages from the repositories
RUN apt update -y

# Install a couple of packages to successfully install postgresql server locally
RUN apt install -y build-essential libpq-dev

# Update python modules to successfully build the required modules
RUN pip install --upgrade pip setuptools wheel

COPY . .

RUN pip install -r requirements.txt

# Export the password. 
ENV POSTGRES_PASSWORD=mypassword
ENV DB_USERNAME=myuser
ENV DB_PASSWORD=${POSTGRES_PASSWORD}
ENV DB_HOST=10.100.242.197
ENV DB_PORT=5432
ENV DB_NAME=mydatabase


CMD ["python", "app.py"]